# Generated by Django 4.2.10 on 2024-02-22 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_alter_category_title_alter_events_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
